### ISSUE TITLE
Sugestões de melhorias

### ISSUE THREAD

**Issue by germanyn** [LucasGSeabra/dnd-monster-reference#1]
1. Nunca terminar URLs com `/`, isso confunde na hora de juntar com paths relativos, que sempre podem passar a iniciar com barra, ex: `/monsters`, `/classes`, `/races/half-elf`
https://github.com/LucasGSeabra/dnd-monster-reference/blob/9c8bd1d574f08018efaacaf1f0bfaeb099302701/src/services/api.js#L3

2. O axios dá suporte ao parâmetro `params` para passar query strings, o que é uma mão na roda, no teu caso
```
api.get('', {
  params: {
    fields: ['slugs', 'name', 'challenge_rating'].join(),
    limit: 100,
    ordering: 'slug',
  }
})...
```
https://github.com/LucasGSeabra/dnd-monster-reference/blob/9c8bd1d574f08018efaacaf1f0bfaeb099302701/src/pages/LandingPage/index.jsx#L15

**Comment by LucasGSeabra** [comment]
Cara, muito obrigado, não sabia dos parâmetros do axios, vou dar uma olhada
melhor na documentação dele até.
Vou ver se até o fim de semana eu deixo ele meio que pronto pra testar um
deploy.
